server:
  port: 8080

spring:
  datasource:
    test1:
      username: root
      password: 123456
      url: jdbc:mysql://192.168.189.129:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
    test2:
      username: root
      password: 123456
      url: jdbc:mysql://192.168.189.129:3306/db2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.mzd.multipledatasources.mapper: debug
